Create set-volume.mdx
100mslive/react-native-hms pull request #390
Opened 2021-11-25 13:36 UTC by samarthjain10

2021-11-26 11:18 UTC, gzerad requested changes

2021-11-26 11:18 UTC, gzerad commented on documentation/features/set-volume.mdx
> +This is a android only API. It allows you to vary the volume level of the remote peer individually for yourself.
pls remove android only

2021-11-26 11:18 UTC, gzerad commented on documentation/features/set-volume.mdx
> +Volume can vary from 0(min) to 1(max).
this will be updated to 0 min to 10 max for both android and ios from next release. Also we should mention 1.0 is default

2021-11-26 11:18 UTC, gzerad commented on documentation/features/set-volume.mdx
> +This is a android only API. It allows you to vary the volume level of the remote peer individually for yourself.
It allows you to locally vary the volume level  of the remote peer's audio track.

2021-12-06 06:13 UTC, ygit commented
@samarthjain10 can you update this PR?

2021-12-06 08:04 UTC, ygit approved these changes

2021-12-06 08:04 UTC, merged